### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ciotorcristian** [vibhavnirmal/InstaChatSave#1]
It can't convert all json file. It give an error:
 Traceback (most recent call last):
  File "C:\Users\cioto\OneDrive\Desktop\InstaChatSave-master\Messages.py", line 25, in <module>
    if(media["conversation"][i].get("text")):
IndexError: list index out of range
What should i modify for it to convert all messages. My messages.json is about 7941kb

**Comment by vibhavnirmal** [comment]
Try Increasing the range of the loop...

for i in range(**_here add 2 or 3 more zeros at the end_**)

e.g. 

`for i in range (100000000):`

maybe this will work

I will try to remove that hardcoded thing in my next commit..
